import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ShieldCheck } from "lucide-react";
import { type FormEvent, useState } from "react";
import { passphraseOf } from "@/live/name";
import { actionFailed } from "@/live/notices";
import { api } from "./api";

/**
 * The way in.
 *
 * The credential is the passphrase an administrator already has — the one that
 * signs their name in a call. What the configuration holds is the signature it
 * produces, which is public and printed beside that name in every room they
 * join. Knowing a signature grants nothing; producing one is the whole of the
 * proof.
 *
 * The field says nothing about what a passphrase should look like, and that is
 * deliberate: an administrator's is generated by the server and kept in a
 * password manager, not thought of at this screen.
 *
 * It accepts `Alice#secret` as readily as `secret`, because that is the shape
 * this application has taught everybody who uses it and there is no reason for
 * one field to keep a different rule. Typing the form people know used to be
 * refused with a sentence saying the passphrase was wrong, at a moment when it
 * was right.
 */
export function SignIn({ onIn }: { onIn: () => void }) {
	const [passphrase, setPassphrase] = useState("");
	const [busy, setBusy] = useState(false);

	const submit = async (event: FormEvent) => {
		event.preventDefault();
		if (busy || !passphrase) return;

		setBusy(true);

		try {
			await api.signIn(passphraseOf(passphrase));
			onIn();
		} catch (err) {
			// A refused passphrase is an event, and the field is cleared for the
			// next attempt. Kept as a banner it would sit under an empty field
			// describing an attempt that is already over.
			actionFailed(err instanceof Error ? err.message : String(err));
			setPassphrase("");
		} finally {
			setBusy(false);
		}
	};

	return (
		<main className="grid min-h-full place-items-center bg-bg p-6 text-fg">
			<form onSubmit={submit} className="flex w-full max-w-sm flex-col gap-4">
				<header className="flex flex-col items-center gap-2 text-center">
					<ShieldCheck className="size-8 text-fg-muted" />
					<h1 className="font-semibold text-xl tracking-tight">Management</h1>
					<p className="text-fg-muted text-sm">
						Enter your passphrase.
					</p>
				</header>

				<Input
					type="password"
					value={passphrase}
					onChange={(event) => setPassphrase(event.target.value)}
					placeholder="Passphrase"
					aria-label="Passphrase"
					autoComplete="current-password"
					// biome-ignore lint/a11y/noAutofocus: the page exists to be typed into
					autoFocus
					maxLength={200}
				/>

				<Button type="submit" size="lg" disabled={!passphrase || busy}>
					{busy ? "Signing in…" : "Sign in"}
				</Button>
			</form>
		</main>
	);
}
