import { Identity } from "@/components/room/Identity";
import { LanguagePicker } from "@/components/room/LanguagePicker";
import { MicLevel } from "@/components/room/MicLevel";
import { RoomTitle } from "@/components/room/RoomTitle";
import { Sealed } from "@/components/room/Sealed";
import { SelfView } from "@/components/room/SelfView";
import { Button } from "@/components/ui/button";
import { useT } from "@/hooks/useT";
import { chosenRelay, deployment, rememberRelay } from "@/live/api";
import { devicesAvailable, insecureReason } from "@/live/context";
import { ServerPicker } from "@/components/room/ServerPicker";
import { parseName } from "@/live/name";
import { type Relay as OfferedRelay, relays } from "@/live/relays";
import { remember } from "@/live/remember";
import { type LocalVideoTrack, createLocalVideoTrack } from "livekit-client";
import { cn } from "@/lib/utils";
import { ArrowLeft, Mic, MicOff, ShieldAlert, UserRound, Video, VideoOff } from "lucide-react";
import { type ReactNode, useEffect, useRef, useState } from "react";

/*
 * The keys below still say the name this was called before.
 *
 * Deliberate, and not an oversight to tidy. They are what a browser already has
 * written down: a display name, a device choice, a language, an identity that
 * keeps somebody the same person across a reload. Renaming them renames nothing
 * — it abandons all of it, and everybody using this finds themselves nameless
 * and back in English on the morning after a deployment.
 */
const NAME_KEY = "meet-live.name";
const DEVICES_KEY = "meet-live.devices";

/*
 * The passphrase, kept so that it is already in the field the next time.
 *
 * This was deliberately not stored once, and the objection was sound as far as
 * it went: local storage is shared with every tab on this origin and outlives
 * the session, so a browser two people use hands the second of them the first
 * one's name. What that objection was weighed against, though, was a passphrase
 * nobody could remember — an administrator's is eleven characters generated by
 * the server — and a field somebody retypes from a password manager on every
 * visit is a field most people stop filling in.
 *
 * So it is worth being clear about what is being kept, and the first version of
 * this was not: it said the passphrase proves a display name and nothing else,
 * that there is no account behind it and nothing it can spend, and that the
 * worst it buys is the use of somebody's name in a meeting.
 *
 * That undersells it in two ways that have both mattered since.
 *
 * It is what makes somebody the host of a room they opened, and a host moves the
 * call to another machine, removes people, mutes them and ends the meeting. And
 * this field is where an administrator types an administrator passphrase — the
 * join endpoint tests the same value against the administrator list — so an
 * administrator who signs into a room this way leaves that credential here in
 * the clear.
 *
 * It is kept anyway, deliberately, and the trade is the one at the top of this
 * comment: the alternative is retyping on every visit, which is how a field
 * stops being filled at all. Somebody weighing it again should weigh the real
 * cost above rather than the gentler claim this used to make.
 *
 * The sealing word for an encrypted call is a different secret and is not kept
 * anywhere.
 *
 * It is still offered to the password manager as well, which is the better home
 * of the two and the only one that syncs to somebody's other devices. This is
 * the copy that guarantees the field is filled.
 *
 * Emptying the field and joining forgets it, because what is written down is
 * whatever was last joined with.
 */
const PASSPHRASE_KEY = "meet-live.passphrase";

export interface Choices {
	name: string;
	/** Never leaves this tab except in the join request. */
	passphrase: string;
	/**
	 * A word the people in the call agree on, which the media is encrypted with.
	 *
	 * Never leaves this tab at all — not in the join request, not in the token,
	 * nowhere. It is combined with the room name in the browser and the result
	 * encrypts every frame before it is sent, so the relay carrying the call
	 * forwards something it cannot read.
	 *
	 * Empty is the ordinary case and the default. Somebody who does not know
	 * this exists has a call exactly as they always did.
	 */
	secret: string;
	camera: boolean;
	microphone: boolean;
	/**
	 * Which relay to hold the call on, or empty for whichever measures fastest.
	 *
	 * Offered because the measurement is a guess made in a second and a half,
	 * and somebody who has just had a bad call on the relay it keeps choosing
	 * knows something it does not. Empty is the default and stays the default:
	 * the automatic answer is right nearly always, and a picker that opened
	 * pre-set to a machine would be asking everybody to have an opinion about
	 * infrastructure.
	 */
	relay: string;
}

/**
 * Device check before entering a room.
 *
 * The camera starts off and the microphone starts on, and both remember what was
 * chosen last time. Defaulting the camera on means the light comes on before
 * anybody has decided to be seen, which is the wrong way round for somebody
 * joining late or from somewhere they would rather not show.
 */
export interface PreJoinProps {
	room: string;
	onRoomChange: (room: string) => void;
	onJoin: (choices: Choices) => Promise<void>;
	/**
	 * Somebody who arrived on an invitation.
	 *
	 * They have a name to choose and nothing else to answer: the link is what
	 * lets them in, the room was decided by whoever sent it, and a passphrase is
	 * the thing an invitation exists to avoid needing. So the passphrase field
	 * goes, and so does the ability to rename the room out from under the
	 * invitation.
	 */
	guest?: boolean;
	/**
	 * Somebody already signed in, and the machine they chose in the lobby.
	 *
	 * When this is set the screen keeps only the half of itself that is about
	 * devices. Who they are was settled at the sign-in, where the room is held
	 * was settled in the lobby, and asking either again is asking somebody to
	 * answer a question they have already answered — which is what the name and
	 * passphrase fields were doing to every signed-in person, on every join.
	 */
	as?: { name: string; relay: string };
	/** Back to wherever this screen was reached from, where there is such a place. */
	onBack?: () => void;
}

export function PreJoin({ room, onRoomChange, onJoin, guest = false, as, onBack }: PreJoinProps) {
	// Checked before anything reaches for a device, so the page explains why it
	// cannot rather than failing on a property that is simply not there.
	if (!devicesAvailable()) {
		return <Unavailable reason={insecureReason()} />;
	}

	return (
		<Form
			room={room}
			onRoomChange={onRoomChange}
			onJoin={onJoin}
			guest={guest}
			as={as}
			onBack={onBack}
		/>
	);
}

/**
 * The frame both states of this screen sit in.
 *
 * One row above everything saying what this is and in what language, the state
 * itself in the middle, and the licence at the foot. The language picker is
 * needed most on the state that cannot be joined from: somebody who lands on the
 * dead end in a language they do not read has no way to find out why.
 */
function Page({ children }: { children: ReactNode }) {
	const t = useT();

	return (
		<main className="flex min-h-full flex-col gap-6 p-5 sm:p-6">
			<header className="flex items-center justify-between gap-4">
				<div className="flex items-center gap-2">
					{/*
					 * The mark this deployment already serves, rather than a second
					 * copy of it kept in a component. One file draws it, and the tab
					 * and the screen cannot come to disagree about what it looks
					 * like.
					 */}
					<img src="/favicon.svg" alt="" className="size-5 rounded-[5px]" />
					<span className="font-semibold text-[13px] tracking-tight">Tomoshibi</span>
				</div>

				<div className="flex items-center gap-2">
					{/*
					 * The way to one's own account, from the page everybody starts on.
					 *
					 * An anchor rather than a route: the account pages are a separate
					 * document with their own session cookie, and nothing about them
					 * belongs in the bundle somebody loads to join a call. It is here
					 * rather than behind a menu because somebody who has been given an
					 * account has been told to go and change the passphrase they were
					 * sent, and a link they have to hunt for is one they do not follow.
					 */}
					<a
						href="/account"
						className={cn(
							"flex items-center gap-1.5 rounded-md border border-border px-2.5 py-1.5",
							"text-[12px] text-fg-muted transition-colors hover:bg-surface-hi hover:text-fg",
						)}
					>
						<UserRound className="size-3.5" />
						<span className="hidden sm:inline">{t("User console")}</span>
					</a>

					<LanguagePicker />
				</div>
			</header>

			<div className="flex flex-1 items-center justify-center">{children}</div>

			<Source />
		</main>
	);
}

/**
 * Where the code running this can be read.
 *
 * An obligation rather than a courtesy, and one that only a page can discharge.
 * This is licensed under the AGPL, whose thirteenth section says that offering
 * people the use of a program over a network obliges the operator to offer them
 * its source — and everybody being offered the use of this one arrives here.
 *
 * The address comes from the server because a deployment running a changed copy
 * owes its visitors that copy rather than this one. Where a server says nothing,
 * nothing is drawn: an offer of somebody else's source is worse than none, since
 * it looks discharged.
 */
function Source() {
	const [source, setSource] = useState("");

	useEffect(() => {
		let live = true;

		void deployment().then((said) => {
			if (live) setSource(said.source);
		});

		return () => {
			live = false;
		};
	}, []);

	if (!source) return null;

	return (
		<a
			href={source}
			target="_blank"
			rel="noreferrer"
			className="absolute inset-x-0 bottom-3 text-center text-[11px] text-fg-muted/60 transition-colors hover:text-fg-muted"
		>
			{/* Not translated, and not an oversight. It is the name of the licence
			    this is under, which is the same string in every language, and the
			    word beside it is what the link goes to. */}
			AGPL-3.0 · source
		</a>
	);
}

function Form({ room, onRoomChange, onJoin, guest = false, as, onBack }: PreJoinProps) {
	const t = useT();
	const [name, setName] = useState(() => localStorage.getItem(NAME_KEY) ?? "");
	const [secret, setSecret] = useState(() => localStorage.getItem(PASSPHRASE_KEY) ?? "");
	const [devices, setDevices] = useState(remembered);
	const [track, setTrack] = useState<LocalVideoTrack>();
	const [joining, setJoining] = useState(false);

	// Empty means whichever measures fastest, which is what nearly everybody
	// wants and what nobody should have to choose. What is not empty is what
	// somebody already chose — in the lobby, a screen ago — and this used to
	// start blank regardless, so a machine picked deliberately came back as
	// "whichever is fastest" on the very next page.
	const [sealWord, setSealWord] = useState("");
	const [relay, setRelay] = useState(() => as?.relay ?? chosenRelay());
	const [servers, setServers] = useState<OfferedRelay[]>([]);
	const [offerChoice, setOfferChoice] = useState(false);

	/*
	 * What the password manager was last offered, so it is not offered again.
	 *
	 * Storing a credential is a prompt: Chromium asks whether to save it, every
	 * time, and it asks whether or not it already holds exactly that pair. The
	 * passphrase field is filled from storage on load, so somebody who joins a
	 * room, leaves, and joins another is answering the same question about the
	 * same secret on every join. Enough of those and the answer stops being read.
	 *
	 * Seeded with what the page opened holding, which is the whole trick: a
	 * passphrase restored from the last visit has been offered before, and one
	 * that differs from it is the only thing worth offering now. A person who
	 * changes their passphrase is asked once, at the moment they changed it.
	 *
	 * A ref rather than state because nothing on screen depends on it, and it
	 * must survive the re-render that a join causes.
	 */
	const offered = useRef(`${localStorage.getItem(NAME_KEY) ?? ""}\u0000${localStorage.getItem(PASSPHRASE_KEY) ?? ""}`);

	// Held in a ref as well, so the cleanup below stops whatever is current
	// rather than whatever was current when the effect last ran.
	const current = useRef<LocalVideoTrack>();

	useEffect(() => {
		let live = true;

		if (!devices.camera) {
			current.current?.stop();
			current.current = undefined;
			setTrack(undefined);
			return;
		}

		createLocalVideoTrack()
			.then((made) => {
				if (!live) {
					made.stop();
					return;
				}
				current.current = made;
				setTrack(made);
			})
			.catch(() => {
				// A refused camera is an answer. The switch falls back to off so
				// the preview and the control agree.
				if (live) setDevices((held) => ({ ...held, camera: false }));
			});

		return () => {
			live = false;
		};
	}, [devices.camera]);

	// Asked once. The list changes when a machine is brought up or taken away,
	// which is not a thing that happens while somebody is looking at a join
	// screen — and asking again on a timer would be a request per visitor per
	// minute for an answer that does not move.
	useEffect(() => {
		let live = true;

		void relays().then((offered) => {
			if (!live) return;

			setServers(offered.relays);

			// Only where there is a choice to make. One relay is not a choice,
			// and a deployment that will not act on a preference would be
			// offering a control that does nothing.
			setOfferChoice(offered.measure && offered.relays.length > 1);
		});

		return () => {
			live = false;
		};
	}, []);

	// Stopped only when the screen goes away for good. The track itself is handed
	// to the room on join, so tearing it down on every render would drop the
	// preview and prompt again a moment later.
	useEffect(() => () => current.current?.stop(), []);

	/*
	 * Two ways in, and one of them is not drawn.
	 *
	 * The field below is the one this teaches, because a field is the only shape
	 * a password manager can see — the whole reason nobody could remember their
	 * passphrase is that it used to be the half of this one after a hash, which
	 * is invisible to every manager ever written.
	 *
	 * `Alice#secret` still works, and goes on working without being advertised.
	 * It is the form this application taught everybody who has used it, and a
	 * syntax that quietly stops being accepted is worse than one that is no
	 * longer mentioned. The field wins where both are filled, since it is the
	 * one somebody can see.
	 */
	const { name: typedName, passphrase: written } = parseName(name);

	// Whoever is signed in, where somebody is. Their name is already theirs and
	// their signature comes from the session, so nothing is typed and nothing is
	// sent — a passphrase in the request would be a second answer to a question
	// already settled, and the one that wins would be whichever the server read
	// first.
	const display = as ? as.name : typedName;
	const passphrase = as ? "" : secret || written;

	const submit = async () => {
		if (!display || joining) return;

		localStorage.setItem(NAME_KEY, display);
		localStorage.setItem(DEVICES_KEY, JSON.stringify(devices));

		// Whatever was last joined with, which means clearing the field and
		// joining is how somebody takes it back off this machine.
		if (passphrase) localStorage.setItem(PASSPHRASE_KEY, passphrase);
		else localStorage.removeItem(PASSPHRASE_KEY);

		// And offered to the password manager, which keeps it better than this
		// can and carries it to the same person's other devices. Once, for any
		// given pair: the offer is a prompt, and one that arrives on every join
		// to ask about a secret the browser already holds is one nobody reads.
		const pair = `${display}\u0000${passphrase}`;
		if (passphrase && pair !== offered.current) {
			offered.current = pair;
			void remember(display, passphrase);
		}

		setJoining(true);

		try {
			await onJoin({
				name: display,
				passphrase,
				secret: sealWord,
				relay: as ? as.relay : relay,
				...devices,
			});
		} catch {
			// Reported by whoever tried, which holds the room object that has to
			// be torn down and the words for what went wrong. Caught here all the
			// same, because a rejection nobody catches is a red line in a console
			// and nothing at all on the screen.
		} finally {
			/*
			 * Put back whether it worked or not, which it was not doing at all.
			 * A join that was refused — a room only administrators may open, a
			 * name the server would not have — left the button reading "Joining"
			 * for ever, with a notice beside it saying why and no way to act on
			 * it. The only way out of this screen was to reload it.
			 *
			 * On success this runs into a screen that has already been replaced,
			 * which costs nothing: the room is mounted by then and nobody is
			 * looking at this button.
			 */
			setJoining(false);
		}
	};

	return (
		<Page>
			{/*
			 * Two columns where the screen is wider than it is tall and there is
			 * room for both, one column otherwise, the picture always first.
			 *
			 * Keyed to the shape of the viewport and not only its width, because
			 * the arrangement this replaces is worst on a screen that is wide and
			 * short — a phone turned on its side, or a window dragged flat. There
			 * a stacked picture is taller than the screen it is on, and the reader
			 * scrolls past their own face to reach the button.
			 */}
			<div className="flex w-full max-w-6xl flex-col gap-6 md:landscape:flex-row md:landscape:items-stretch md:landscape:gap-8">
				<div className="md:landscape:flex-[1.35]">
					<SelfView track={track}>
						{/*
						 * The same island the call puts these two switches in, in
						 * the same place, so this screen is a rehearsal of the room
						 * rather than a different room.
						 */}
						<div className="-translate-x-1/2 absolute bottom-3 left-1/2 flex items-center gap-1.5 rounded-full border border-border bg-surface/90 p-1.5 shadow-2xl backdrop-blur-md">
							<Button
								variant={devices.microphone ? "secondary" : "danger"}
								size="round"
								className="size-9"
								aria-label={devices.microphone ? t("Mute microphone") : t("Unmute microphone")}
								aria-pressed={devices.microphone}
								onClick={() => setDevices((held) => ({ ...held, microphone: !held.microphone }))}
							>
								{devices.microphone ? <Mic /> : <MicOff />}
							</Button>

							<Button
								variant={devices.camera ? "secondary" : "danger"}
								size="round"
								className="size-9"
								aria-label={devices.camera ? t("Turn camera off") : t("Turn camera on")}
								aria-pressed={devices.camera}
								onClick={() => setDevices((held) => ({ ...held, camera: !held.camera }))}
							>
								{devices.camera ? <Video /> : <VideoOff />}
							</Button>
						</div>
					</SelfView>

					{/*
					 * Under the picture rather than inside it, because it answers a
					 * different question from the switch above it. The switch says
					 * whether the microphone will be on; this says whether it works,
					 * which nothing on this screen said until now — and this screen
					 * exists to answer exactly those two things about the two
					 * devices, which is what the comment beside the form says it is
					 * for.
					 */}
					<div className="mt-2.5 px-1">
						<MicLevel on={devices.microphone} />
					</div>
				</div>

				<form
					className="flex flex-col justify-center gap-5 md:landscape:min-w-[17rem] md:landscape:flex-1"
					onSubmit={(event) => {
						event.preventDefault();
						void submit();
					}}
				>
					{/*
					 * Everything above the button belongs to somebody who has not
					 * answered these questions yet.
					 *
					 * Somebody signed in has answered all of them: their name at the
					 * sign-in, the room and the machine in the lobby. What was left
					 * on this screen was a room code to confirm, a name to type, a
					 * passphrase to type, and a server to pick — four answers to
					 * questions already settled, between them and a meeting they had
					 * already said they wanted to be in.
					 *
					 * So for them this page is the one thing nobody can answer in
					 * advance: whether the camera is pointing at the right thing and
					 * whether the microphone is the right one.
					 */}
					{/*
					 * The name, always, and editable only where it is still a
					 * question.
					 *
					 * Taking it away entirely left a button alone in half a screen,
					 * which reads as a page that failed to load the rest of itself —
					 * and it took with it the one thing this screen is for
					 * confirming: that the meeting somebody is about to walk into is
					 * the one they meant. It is not a field for somebody who came
					 * through the lobby, because they typed it there; it is a
					 * heading, which is what it always was underneath.
					 */}
					{as ? (
						<div className="flex flex-col gap-2">
							{/*
							 * The way back, because this screen is a step and not a
							 * destination. Somebody who came through the lobby and
							 * changed their mind about which meeting they wanted had
							 * nothing to press: the only exits were joining a call
							 * they did not want and the browser's back button.
							 */}
							<button
								type="button"
								onClick={onBack}
								className={cn(
									"flex w-fit items-center gap-1.5 rounded-md px-1.5 py-1 -ml-1.5",
									"text-[12px] text-fg-muted transition-colors hover:bg-surface-hi hover:text-fg",
								)}
							>
								<ArrowLeft className="size-3.5" />
								{t("Back")}
							</button>

							<h1 className="readout truncate font-semibold text-fg text-xl tracking-tight">
								{room}
							</h1>
						</div>
					) : (
						<RoomTitle room={room} onChange={onRoomChange} fixed={guest} />
					)}

					{/*
					 * Nothing to fill in for somebody signed in.
					 *
					 * Their name is already theirs and their signature comes from
					 * the session, so both fields were asking for answers that had
					 * already been given — and one of them was asking for a
					 * passphrase on a screen they reach after having typed it. What
					 * is left is the half of this page that is about devices, which
					 * is the half nobody can answer in advance.
					 */}
					{!as && (
						<div className="flex flex-col gap-2">
							<Identity
								name={name}
								passphrase={secret}
								onName={setName}
								onPassphrase={setSecret}
								nameOnly={guest}
							/>

							{/* One line, which changes rather than doubling: what a
							    passphrase is for until there is one, and what it did
							    once there is. */}
							<p className="text-fg-muted text-xs leading-snug">
								{guest
									? t("You were invited to this room. Choose a name and go in.")
									: passphrase
										? t("Only you can join as {name}", { name: display || "?" })
										: t("Add a passphrase to keep your name, and to run the room you open.")}
							</p>
						</div>
					)}

					{/* Folded away, under the identity, because most calls do not
					    want it and the ones that do want it before they start.
					    Offered to a guest as much as to anybody: the word is not
					    the passphrase and knowing it is what the invitation
					    assumes. */}
					<Sealed value={sealWord} onChange={setSealWord} />

					{/* Below the identity and above the button, because it is the
					    last thing anybody would change and the first thing nobody
					    should have to. Absent entirely where there is nothing to
					    choose between. */}
					{offerChoice && !as && (
						<ServerPicker
							relays={servers}
							value={relay}
							onChange={(chosen) => {
								setRelay(chosen);

								// Written down here as well as in the lobby.
								// Only the lobby was remembering, so a change
								// made on this screen survived exactly until
								// the page was reloaded.
								rememberRelay(chosen);
							}}
						/>
					)}

					<Button type="submit" variant="primary" size="lg" className="w-full" disabled={!display || joining}>
						{joining ? t("Joining…") : t("Join")}
					</Button>
				</form>
			</div>
		</Page>
	);
}

/**
 * Why this page cannot open a camera.
 *
 * A dead end rather than a warning, because there is nothing to try: the page
 * has to be loaded from somewhere else before any of this works.
 */
function Unavailable({ reason }: { reason: string }) {
	const t = useT();

	return (
		<Page>
			<div className="w-full max-w-md space-y-4 text-center">
				<ShieldAlert className="mx-auto size-10 text-fg-muted" />
				<h1 className="font-semibold text-2xl tracking-tight">{t("Can't use your camera or microphone")}</h1>
				<p className="text-fg-muted text-sm">{reason}</p>
			</div>
		</Page>
	);
}

/** What was chosen last time, or the defaults on a first visit. */
/**
 * The devices as they were left, which is also what a reload should come back
 * with. Exported for that: somebody rejoining after a refresh has already made
 * these two decisions and should not be asked again.
 */
/**
 * The name last joined under, for a reload that is going straight back in.
 *
 * Whatever was typed, including anything after a hash: the passphrase half is
 * dropped on the way out, because a rejoin carries the identity it already has
 * and does not need to prove the name again.
 */
export function rememberedName(): string {
	return parseName(localStorage.getItem(NAME_KEY) ?? "").name;
}

export function remembered(): { camera: boolean; microphone: boolean } {
	const fallback = { camera: false, microphone: true };

	try {
		const stored = localStorage.getItem(DEVICES_KEY);
		if (!stored) return fallback;

		const parsed = JSON.parse(stored) as Partial<typeof fallback>;
		return {
			camera: parsed.camera ?? fallback.camera,
			microphone: parsed.microphone ?? fallback.microphone,
		};
	} catch {
		return fallback;
	}
}
