import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { Refused } from "@/live/api";
import { remember } from "@/live/remember";
import { PreJoin } from "./PreJoin";

vi.mock("@/live/remember", () => ({ remember: vi.fn(async () => {}) }));

/*
 * The way out of this screen when the server says no.
 *
 * A join can be refused for reasons nobody typing here can see coming: a room
 * only administrators may open, a name the server will not have, a rate limit.
 * Every one of those left the button reading "Joining…" for good, with a notice
 * beside it explaining why and nothing to press. The only way on was to reload
 * the page, which is not a thing an interface should ever ask for.
 *
 * It went unnoticed because the successful path hides it: on a join that works
 * this screen is replaced, so the button nobody put back is a button nobody
 * sees.
 */

const camera = { stop: vi.fn(), attach: vi.fn(), detach: vi.fn() };

beforeEach(() => {
	localStorage.clear();
	vi.mocked(remember).mockClear();

	// The preview asks for a camera on mount. Nothing here is about the picture,
	// and a real request would hang in a test environment that has no devices.
	vi.mock("livekit-client", async (original) => ({
		...(await original<typeof import("livekit-client")>()),
		createLocalVideoTrack: () => Promise.resolve(camera),
	}));

	vi.stubGlobal(
		"fetch",
		vi.fn(async () => new Response(JSON.stringify({ openedBy: "anyone", source: "" }))),
	);

	// This screen refuses to draw a form where a browser would not hand over a
	// camera, and a test environment is exactly such a browser. Both halves of
	// that check are answered here so the form under test is the one people see.
	Object.defineProperty(window, "isSecureContext", { value: true, configurable: true });
	Object.defineProperty(navigator, "mediaDevices", {
		value: { enumerateDevices: async () => [], addEventListener() {}, removeEventListener() {} },
		configurable: true,
	});
});

afterEach(() => {
	vi.unstubAllGlobals();
	localStorage.clear();
});

function open(onJoin: (choices: unknown) => Promise<void>) {
	render(<PreJoin room="standup" onRoomChange={vi.fn()} onJoin={onJoin as never} />);
}

async function joinAs(name: string) {
	fireEvent.change(screen.getByLabelText("Your name"), { target: { value: name } });
	fireEvent.click(screen.getByRole("button", { name: "Join" }));
}

async function joinAsWith(name: string, passphrase: string) {
	fireEvent.change(screen.getByLabelText("Your name"), { target: { value: name } });
	fireEvent.change(screen.getByLabelText("Passphrase"), { target: { value: passphrase } });
	fireEvent.click(screen.getByRole("button", { name: "Join" }));
}

describe("PreJoin", () => {
	it("gives the button back when the server refuses", async () => {
		const refuse = vi.fn(() => Promise.reject(new Error("that room has not been opened")));

		open(refuse as never);
		await joinAs("Alex");

		await waitFor(() => expect(refuse).toHaveBeenCalled());

		// Pressable again, saying what it says when nothing is happening. Without
		// this the screen is a dead end with a notice on it.
		await waitFor(() => {
			const button = screen.getByRole("button", { name: "Join" });
			expect(button.textContent).toBe("Join");
			expect((button as HTMLButtonElement).disabled).toBe(false);
		});
	});

	// And says so while it is waiting, which is the half that already worked.
	it("says what it is doing while the server thinks", async () => {
		let settle: () => void = () => {};
		const slow = vi.fn(() => new Promise<void>((resolve) => (settle = resolve)));

		open(slow as never);
		await joinAs("Alex");

		await waitFor(() => expect(screen.getByRole("button", { name: "Joining…" })).toBeDefined());

		await act(async () => {
			settle();
		});
	});

	// Twice through is one join, not two. A second press while the first is out
	// would mint a second identity and evict the first from the room.
	it("cannot be pressed twice while it is waiting", async () => {
		const slow = vi.fn(() => new Promise<void>(() => {}));

		open(slow as never);
		await joinAs("Alex");

		await waitFor(() => expect(slow).toHaveBeenCalledTimes(1));

		fireEvent.click(screen.getByRole("button", { name: "Joining…" }));
		expect(slow).toHaveBeenCalledTimes(1);
	});

	/*
	 * A passphrase generated by the server is eleven characters of nothing
	 * memorable. Asked for it on every visit, most people stop giving one — and a
	 * name nobody signs is the thing the whole mechanism exists to prevent.
	 *
	 * The password manager is offered it too and keeps it better, but nothing
	 * makes a manager fill a field; this is the copy that does.
	 */
	it("has the passphrase waiting on the next visit", async () => {
		const succeed = vi.fn(() => Promise.resolve());

		open(succeed as never);
		fireEvent.change(screen.getByRole("textbox", { name: "Your name" }), {
			target: { value: "Alex" },
		});
		fireEvent.change(screen.getByLabelText("Passphrase"), { target: { value: "quietly" } });
		fireEvent.click(screen.getByRole("button", { name: "Join" }));

		await waitFor(() => expect(succeed).toHaveBeenCalled());

		cleanup();
		open(succeed as never);

		expect((screen.getByLabelText("Passphrase") as HTMLInputElement).value).toBe("quietly");
		expect((screen.getByRole("textbox", { name: "Your name" }) as HTMLInputElement).value).toBe(
			"Alex",
		);
	});

	// The way back off a machine that is not yours, and the only one there needs
	// to be: what is kept is whatever was last joined with.
	it("forgets it when somebody clears the field and joins", async () => {
		const succeed = vi.fn(() => Promise.resolve());

		localStorage.setItem("meet-live.passphrase", "quietly");
		open(succeed as never);

		expect((screen.getByLabelText("Passphrase") as HTMLInputElement).value).toBe("quietly");

		fireEvent.change(screen.getByRole("textbox", { name: "Your name" }), {
			target: { value: "Alex" },
		});
		fireEvent.change(screen.getByLabelText("Passphrase"), { target: { value: "" } });
		fireEvent.click(screen.getByRole("button", { name: "Join" }));

		await waitFor(() => expect(succeed).toHaveBeenCalled());
		expect(localStorage.getItem("meet-live.passphrase")).toBeNull();
	});
});

/*
 * Offering a passphrase to the password manager is a prompt, not a write.
 *
 * Chromium asks whether to save it — every time it is offered, and whether or
 * not it already holds exactly that pair. The field is filled from storage on
 * load, so joining a second room means answering the same question about the
 * same secret again, and the third time somebody stops reading the question at
 * all. That is the failure: not a broken save, a trained dismissal.
 *
 * It cannot be caught by looking at the screen, because the prompt is the
 * browser's and never appears in the document. So what is asserted is the call.
 */
describe("the password manager", () => {
	it("is offered a passphrase that was just entered", async () => {
		open(async () => {});
		await joinAsWith("Alex", "correct horse");

		await waitFor(() => expect(remember).toHaveBeenCalledWith("Alex", "correct horse"));
	});

	it("is not offered the same one twice", async () => {
		open(async () => {});

		await joinAsWith("Alex", "correct horse");
		await waitFor(() => expect(remember).toHaveBeenCalledTimes(1));

		fireEvent.click(screen.getByRole("button", { name: "Join" }));
		await waitFor(() => expect(remember).toHaveBeenCalledTimes(1));
	});

	// The case that made this worth fixing: a returning visitor. The field is
	// filled from storage before anybody touches it, and the pair it holds was
	// offered on the visit that stored it.
	it("is not offered one restored from a previous visit", async () => {
		localStorage.setItem("meet-live.name", "Alex");
		localStorage.setItem("meet-live.passphrase", "correct horse");

		open(async () => {});
		fireEvent.click(screen.getByRole("button", { name: "Join" }));

		await waitFor(() => expect(screen.getByRole("button", { name: "Join" })).toBeDefined());
		expect(remember).not.toHaveBeenCalled();
	});

	it("is offered again once it changes", async () => {
		open(async () => {});

		await joinAsWith("Alex", "correct horse");
		await waitFor(() => expect(remember).toHaveBeenCalledTimes(1));

		await joinAsWith("Alex", "battery staple");
		await waitFor(() => expect(remember).toHaveBeenCalledTimes(2));
		expect(remember).toHaveBeenLastCalledWith("Alex", "battery staple");
	});
});

/*
 * A guest of a room held under a scope.
 *
 * The server signs the link's name into the token and mints an issued mark
 * whatever the guest sends, so what this screen owes them is to show the name
 * they will wear rather than ask for one, and to leave alone what this browser
 * has kept about somebody else. The second half is the quiet one: a guest join
 * used to write over the stored name and passphrase with the link's name and
 * nothing, and offer the password manager a pair made of the two — which is a
 * browser that has forgotten its owner's passphrase, and a credential filed
 * under a client's name.
 */
describe("a guest of a scoped room", () => {
	function invitedAs(onJoin: (choices: unknown) => Promise<void>, invitation: object) {
		render(
			<PreJoin
				room="standup@acme"
				onRoomChange={vi.fn()}
				onJoin={onJoin as never}
				guest
				invitation={invitation}
			/>,
		);
	}

	it("joins under the name the link was made for, and sends no passphrase", async () => {
		localStorage.setItem("meet-live.name", "Alex");
		localStorage.setItem("meet-live.passphrase", "quietly");

		const succeed = vi.fn((_choices: unknown) => Promise.resolve());
		invitedAs(succeed, { name: "Client Co" });

		const field = screen.getByRole("textbox", { name: "Your name" }) as HTMLInputElement;
		expect(field.value).toBe("Client Co");
		expect(field.readOnly).toBe(true);

		fireEvent.click(screen.getByRole("button", { name: "Join" }));

		await waitFor(() => expect(succeed).toHaveBeenCalled());

		expect(succeed.mock.calls[0]?.[0]).toMatchObject({ name: "Client Co", passphrase: "" });

		expect(localStorage.getItem("meet-live.name")).toBe("Alex");
		expect(localStorage.getItem("meet-live.passphrase")).toBe("quietly");
		expect(remember).not.toHaveBeenCalled();
	});

	it("lets the guest choose a name where the link did not", async () => {
		const succeed = vi.fn((_choices: unknown) => Promise.resolve());
		invitedAs(succeed, {});

		const field = screen.getByRole("textbox", { name: "Your name" }) as HTMLInputElement;
		expect(field.readOnly).toBe(false);

		fireEvent.change(field, { target: { value: "Sam" } });
		fireEvent.click(screen.getByRole("button", { name: "Join" }));

		await waitFor(() => expect(succeed).toHaveBeenCalled());
		expect(succeed.mock.calls[0]?.[0]).toMatchObject({ name: "Sam", passphrase: "" });
	});

	it("says when the link stops working, and says nothing for one that does not", async () => {
		invitedAs(async () => {}, { until: "2026-03-03T04:00:00Z" });

		expect(screen.getByText(/this link works until/i)).toBeDefined();

		cleanup();
		invitedAs(async () => {}, {});

		expect(screen.queryByText(/this link works/i)).toBeNull();
	});

	// The door of a scoped room is answered by its members, so being turned
	// away by it is the moment to offer the knock, as an invitation-only door's
	// refusal is.
	it("offers to knock when the scope turns somebody away", async () => {
		const refuse = vi.fn(() => Promise.reject(new Refused("not_in_scope", "Only members of acme can join.")));

		render(<PreJoin room="standup@acme" onRoomChange={vi.fn()} onJoin={refuse as never} />);
		await joinAs("Sam");

		await waitFor(() => expect(screen.getByRole("button", { name: "Ask to be let in" })).toBeDefined());
	});
});
