import { Identity } from "@/components/room/Identity";
import { LanguagePicker } from "@/components/room/LanguagePicker";
import { RoomTitle } from "@/components/room/RoomTitle";
import { SelfView } from "@/components/room/SelfView";
import { Button } from "@/components/ui/button";
import { useT } from "@/hooks/useT";
import { deployment } from "@/live/api";
import { devicesAvailable, insecureReason } from "@/live/context";
import { parseName } from "@/live/name";
import { remember } from "@/live/remember";
import { type LocalVideoTrack, createLocalVideoTrack } from "livekit-client";
import { Mic, MicOff, ShieldAlert, Video, VideoOff } from "lucide-react";
import { type ReactNode, useEffect, useRef, useState } from "react";

/*
 * The keys below still say the name this was called before.
 *
 * Deliberate, and not an oversight to tidy. They are what a browser already has
 * written down: a display name, a device choice, a language, an identity that
 * keeps somebody the same person across a reload. Renaming them renames nothing
 * — it abandons all of it, and everybody using this finds themselves nameless
 * and back in English on the morning after a deployment.
 */
const NAME_KEY = "meet-live.name";
const DEVICES_KEY = "meet-live.devices";

/*
 * The passphrase, kept so that it is already in the field the next time.
 *
 * This was deliberately not stored once, and the objection was sound as far as
 * it went: local storage is shared with every tab on this origin and outlives
 * the session, so a browser two people use hands the second of them the first
 * one's name. What that objection was weighed against, though, was a passphrase
 * nobody could remember — an administrator's is eleven characters generated by
 * the server — and a field somebody retypes from a password manager on every
 * visit is a field most people stop filling in.
 *
 * So it is worth being clear about what is being kept. It proves a display name
 * in a call and nothing else. There is no account behind it, nothing it can
 * read, and nothing it can spend; the worst it buys is the use of somebody's
 * name in a meeting. That is a real cost on a shared machine and a small one
 * against never being signed at all.
 *
 * It is still offered to the password manager as well, which is the better home
 * of the two and the only one that syncs to somebody's other devices. This is
 * the copy that guarantees the field is filled.
 *
 * Emptying the field and joining forgets it, because what is written down is
 * whatever was last joined with.
 */
const PASSPHRASE_KEY = "meet-live.passphrase";

export interface Choices {
	name: string;
	/** Never leaves this tab except in the join request. */
	passphrase: string;
	camera: boolean;
	microphone: boolean;
}

/**
 * Device check before entering a room.
 *
 * The camera starts off and the microphone starts on, and both remember what was
 * chosen last time. Defaulting the camera on means the light comes on before
 * anybody has decided to be seen, which is the wrong way round for somebody
 * joining late or from somewhere they would rather not show.
 */
export interface PreJoinProps {
	room: string;
	onRoomChange: (room: string) => void;
	onJoin: (choices: Choices) => Promise<void>;
}

export function PreJoin({ room, onRoomChange, onJoin }: PreJoinProps) {
	// Checked before anything reaches for a device, so the page explains why it
	// cannot rather than failing on a property that is simply not there.
	if (!devicesAvailable()) {
		return <Unavailable reason={insecureReason()} />;
	}

	return <Form room={room} onRoomChange={onRoomChange} onJoin={onJoin} />;
}

/**
 * The frame both states of this screen sit in.
 *
 * One row above everything saying what this is and in what language, the state
 * itself in the middle, and the licence at the foot. The language picker is
 * needed most on the state that cannot be joined from: somebody who lands on the
 * dead end in a language they do not read has no way to find out why.
 */
function Page({ children }: { children: ReactNode }) {
	return (
		<main className="flex min-h-full flex-col gap-6 p-5 sm:p-6">
			<header className="flex items-center justify-between gap-4">
				<div className="flex items-center gap-2">
					{/*
					 * The mark this deployment already serves, rather than a second
					 * copy of it kept in a component. One file draws it, and the tab
					 * and the screen cannot come to disagree about what it looks
					 * like.
					 */}
					<img src="/favicon.svg" alt="" className="size-5 rounded-[5px]" />
					<span className="font-semibold text-[13px] tracking-tight">Tomoshibi</span>
				</div>

				<LanguagePicker />
			</header>

			<div className="flex flex-1 items-center justify-center">{children}</div>

			<Source />
		</main>
	);
}

/**
 * Where the code running this can be read.
 *
 * An obligation rather than a courtesy, and one that only a page can discharge.
 * This is licensed under the AGPL, whose thirteenth section says that offering
 * people the use of a program over a network obliges the operator to offer them
 * its source — and everybody being offered the use of this one arrives here.
 *
 * The address comes from the server because a deployment running a changed copy
 * owes its visitors that copy rather than this one. Where a server says nothing,
 * nothing is drawn: an offer of somebody else's source is worse than none, since
 * it looks discharged.
 */
function Source() {
	const [source, setSource] = useState("");

	useEffect(() => {
		let live = true;

		void deployment().then((said) => {
			if (live) setSource(said.source);
		});

		return () => {
			live = false;
		};
	}, []);

	if (!source) return null;

	return (
		<a
			href={source}
			target="_blank"
			rel="noreferrer"
			className="absolute inset-x-0 bottom-3 text-center text-[11px] text-fg-muted/60 transition-colors hover:text-fg-muted"
		>
			{/* Not translated, and not an oversight. It is the name of the licence
			    this is under, which is the same string in every language, and the
			    word beside it is what the link goes to. */}
			AGPL-3.0 · source
		</a>
	);
}

function Form({ room, onRoomChange, onJoin }: PreJoinProps) {
	const t = useT();
	const [name, setName] = useState(() => localStorage.getItem(NAME_KEY) ?? "");
	const [secret, setSecret] = useState(() => localStorage.getItem(PASSPHRASE_KEY) ?? "");
	const [devices, setDevices] = useState(remembered);
	const [track, setTrack] = useState<LocalVideoTrack>();
	const [joining, setJoining] = useState(false);

	// Held in a ref as well, so the cleanup below stops whatever is current
	// rather than whatever was current when the effect last ran.
	const current = useRef<LocalVideoTrack>();

	useEffect(() => {
		let live = true;

		if (!devices.camera) {
			current.current?.stop();
			current.current = undefined;
			setTrack(undefined);
			return;
		}

		createLocalVideoTrack()
			.then((made) => {
				if (!live) {
					made.stop();
					return;
				}
				current.current = made;
				setTrack(made);
			})
			.catch(() => {
				// A refused camera is an answer. The switch falls back to off so
				// the preview and the control agree.
				if (live) setDevices((held) => ({ ...held, camera: false }));
			});

		return () => {
			live = false;
		};
	}, [devices.camera]);

	// Stopped only when the screen goes away for good. The track itself is handed
	// to the room on join, so tearing it down on every render would drop the
	// preview and prompt again a moment later.
	useEffect(() => () => current.current?.stop(), []);

	/*
	 * Two ways in, and one of them is not drawn.
	 *
	 * The field below is the one this teaches, because a field is the only shape
	 * a password manager can see — the whole reason nobody could remember their
	 * passphrase is that it used to be the half of this one after a hash, which
	 * is invisible to every manager ever written.
	 *
	 * `Alice#secret` still works, and goes on working without being advertised.
	 * It is the form this application taught everybody who has used it, and a
	 * syntax that quietly stops being accepted is worse than one that is no
	 * longer mentioned. The field wins where both are filled, since it is the
	 * one somebody can see.
	 */
	const { name: display, passphrase: written } = parseName(name);
	const passphrase = secret || written;

	const submit = async () => {
		if (!display || joining) return;

		localStorage.setItem(NAME_KEY, display);
		localStorage.setItem(DEVICES_KEY, JSON.stringify(devices));

		// Whatever was last joined with, which means clearing the field and
		// joining is how somebody takes it back off this machine.
		if (passphrase) localStorage.setItem(PASSPHRASE_KEY, passphrase);
		else localStorage.removeItem(PASSPHRASE_KEY);

		// And offered to the password manager, which keeps it better than this
		// can and carries it to the same person's other devices.
		void remember(display, passphrase);

		setJoining(true);

		try {
			await onJoin({ name: display, passphrase, ...devices });
		} catch {
			// Reported by whoever tried, which holds the room object that has to
			// be torn down and the words for what went wrong. Caught here all the
			// same, because a rejection nobody catches is a red line in a console
			// and nothing at all on the screen.
		} finally {
			/*
			 * Put back whether it worked or not, which it was not doing at all.
			 * A join that was refused — a room only administrators may open, a
			 * name the server would not have — left the button reading "Joining"
			 * for ever, with a notice beside it saying why and no way to act on
			 * it. The only way out of this screen was to reload it.
			 *
			 * On success this runs into a screen that has already been replaced,
			 * which costs nothing: the room is mounted by then and nobody is
			 * looking at this button.
			 */
			setJoining(false);
		}
	};

	return (
		<Page>
			{/*
			 * Two columns where the screen is wider than it is tall and there is
			 * room for both, one column otherwise, the picture always first.
			 *
			 * Keyed to the shape of the viewport and not only its width, because
			 * the arrangement this replaces is worst on a screen that is wide and
			 * short — a phone turned on its side, or a window dragged flat. There
			 * a stacked picture is taller than the screen it is on, and the reader
			 * scrolls past their own face to reach the button.
			 */}
			<div className="flex w-full max-w-6xl flex-col gap-6 md:landscape:flex-row md:landscape:items-stretch md:landscape:gap-8">
				<div className="md:landscape:flex-[1.35]">
					<SelfView track={track}>
						{/*
						 * The same island the call puts these two switches in, in
						 * the same place, so this screen is a rehearsal of the room
						 * rather than a different room.
						 */}
						<div className="-translate-x-1/2 absolute bottom-3 left-1/2 flex items-center gap-1.5 rounded-full border border-border bg-surface/90 p-1.5 shadow-2xl backdrop-blur-md">
							<Button
								variant={devices.microphone ? "secondary" : "danger"}
								size="round"
								className="size-9"
								aria-label={devices.microphone ? t("Mute microphone") : t("Unmute microphone")}
								aria-pressed={devices.microphone}
								onClick={() => setDevices((held) => ({ ...held, microphone: !held.microphone }))}
							>
								{devices.microphone ? <Mic /> : <MicOff />}
							</Button>

							<Button
								variant={devices.camera ? "secondary" : "danger"}
								size="round"
								className="size-9"
								aria-label={devices.camera ? t("Turn camera off") : t("Turn camera on")}
								aria-pressed={devices.camera}
								onClick={() => setDevices((held) => ({ ...held, camera: !held.camera }))}
							>
								{devices.camera ? <Video /> : <VideoOff />}
							</Button>
						</div>
					</SelfView>
				</div>

				<form
					className="flex flex-col justify-center gap-5 md:landscape:min-w-[17rem] md:landscape:flex-1"
					onSubmit={(event) => {
						event.preventDefault();
						void submit();
					}}
				>
					<RoomTitle room={room} onChange={onRoomChange} />

					<div className="flex flex-col gap-2">
						<Identity
							name={name}
							passphrase={secret}
							onName={setName}
							onPassphrase={setSecret}
						/>

						{/* One line, which changes rather than doubling: what a
						    passphrase is for until there is one, and what it did
						    once there is. */}
						<p className="text-fg-muted text-xs leading-snug">
							{passphrase
								? t("Only you can join as {name}", { name: display || "?" })
								: t("Add a passphrase so nobody else can use your name.")}
						</p>
					</div>

					<Button type="submit" variant="primary" size="lg" className="w-full" disabled={!display || joining}>
						{joining ? t("Joining…") : t("Join")}
					</Button>
				</form>
			</div>
		</Page>
	);
}

/**
 * Why this page cannot open a camera.
 *
 * A dead end rather than a warning, because there is nothing to try: the page
 * has to be loaded from somewhere else before any of this works.
 */
function Unavailable({ reason }: { reason: string }) {
	const t = useT();

	return (
		<Page>
			<div className="w-full max-w-md space-y-4 text-center">
				<ShieldAlert className="mx-auto size-10 text-fg-muted" />
				<h1 className="font-semibold text-2xl tracking-tight">{t("Can't use your camera or microphone")}</h1>
				<p className="text-fg-muted text-sm">{reason}</p>
			</div>
		</Page>
	);
}

/** What was chosen last time, or the defaults on a first visit. */
function remembered(): { camera: boolean; microphone: boolean } {
	const fallback = { camera: false, microphone: true };

	try {
		const stored = localStorage.getItem(DEVICES_KEY);
		if (!stored) return fallback;

		const parsed = JSON.parse(stored) as Partial<typeof fallback>;
		return {
			camera: parsed.camera ?? fallback.camera,
			microphone: parsed.microphone ?? fallback.microphone,
		};
	} catch {
		return fallback;
	}
}
